# fly.toml app configuration file generated for pulk on 2023-05-08T17:14:32+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "pulk"
primary_region = "arn"
kill_signal = "SIGTERM"
kill_timeout = "5s"

[deploy]
  release_command = "/app/bin/migrate"

[env]
  PHX_HOST = "pulk.fly.dev"
  PORT = "8080"
  PRIMARY_REGION = "arn"
